### ISSUE TITLE
Use mkdirp ^0.5.0

### ISSUE THREAD

**Issue by matthewp** [fs-utils/mkdirp-then#2]
When you install mkdirp-then you get 0.3.5 which contains a bug where if you do not pass in a mode it will ignore your callback, see the commit:

https://github.com/substack/node-mkdirp/commit/6dbdc386a074fe471daaf5e03473db7a90df04fd#diff-168726dbe96b3ce427e7fedce31bb0bcL7

Updating to ^0.5.0 will fix this.

**Comment by matthewp** [comment]
I think this is caused by NPM3. If I install mkdirp-then into an new project I get 0.5.1.  But because NPM3 doesn't nest any more, it's finding 0.3.5 (I guess another dependency of my project is using that) is semver compatible with the "0" listed here. So I'll send a PR with 0.5.0 to be more explicit.

**Comment by ashleygwilliams** [comment]
npmv3 does nest, just not the first installed version of a pkg that is a secondary dependency (i know that's a mouthful, just wanted to make sure you understood) (and then this happens recursively down the tree)

**Comment by matthewp** [comment]
@ashleygwilliams I do understand, I implemented the npm3 algorithm in the browser: https://github.com/stealjs/system-npm/blob/master/npm-crawl.js

However in this case it finds the first version matching compatible with "0" (in my project this is 0.3.5 because of another dep) whereas in NPM 2 it would have installed 0.5.1.

**Comment by ashleygwilliams** [comment]
got it! thanks for pointing out the work you did in the browser! if you could file an issue about this in the docs repo, that'd be great, as i imagine other people will have this issue so it'd be great to document it.
